version: "3.8"
services:
  zoom:
    build: .
    ports:
      - 3000:3000
    volumes:
      - /home/damien/work/zoomClone/:/app
      - /home/damien/work/zoomClone/node_modules:/app/node_modules
    command: npm run devStart
    # > sh -c " && peerjs --port 443 --key peerjs --path /myapp"
  # peer:
  #   image: peerjs/peerjs-server
  #   ports:
  #     - 3001:9000
